#!/bin/bash

if [ $# -lt 1 ]; then
  exit 1
fi

extract() {
  arg="$1"
  pswd="$2"
  cd "$(dirname "$arg")" || exit
  case "$arg" in
  *.tar.bz2)
    tar xjf "$arg" --one-top-level
    local code=$?
    ;;
  *.tar.gz)
    tar xzf "$arg" --one-top-level
    local code=$?
    ;;
  *.bz2)
    bunzip2 "$arg"
    local code=$?
    ;;
  *.gz)
    gunzip "$arg"
    local code=$?
    ;;
  *.tar)
    tar xf "$arg" --one-top-level
    local code=$?
    ;;
  *.tbz2)
    (tar xjf "$arg" --one-top-level)
    local code=$?
    ;;
  *.tgz)
    tar xzf "$arg" --one-top-level
    local code=$?
    ;;
  *.tar.xz)
    a_dir=$(expr "$arg" : '\(.*\).tar.xz')
    saxx
    local code=$?
    ;;
  *.zip)
    a_dir=$(expr "$arg" : '\(.*\).zip')
    saxx
    local code=$?
    ;;
  *.7z)
    a_dir=$(expr "$arg" : '\(.*\).7z')
    saxx
    local code=$?
    ;;
  *.Z)
    uncompress "$arg"
    local code=$?
    ;;
  *.rar)
    a_dir=$(expr "$arg" : '\(.*\).rar')
    mkdir "$a_dir"
    saxx
    local code=$?
    ;;
  *.iso)
    a_dir=$(expr "$arg" : '\(.*\).iso')
    saxx
    local code=$?
    ;;
  *.wim)
    a_dir=$(expr "$arg" : '\(.*\).wim')
    saxx
    local code=$?
    ;;
  *.cab)
    a_dir=$(expr "$arg" : '\(.*\).cab')
    saxx
    local code=$?
    ;;
  *.apm)
    a_dir=$(expr "$arg" : '\(.*\).apm')
    saxx
    local code=$?
    ;;
  *.arj)
    a_dir=$(expr "$arg" : '\(.*\).arj')
    saxx
    local code=$?
    ;;
  *.chm)
    a_dir=$(expr "$arg" : '\(.*\).chm')
    saxx
    local code=$?
    ;;
  *.cpio)
    a_dir=$(expr "$arg" : '\(.*\).cpio')
    saxx
    local code=$?
    ;;
  *.cramfs)
    a_dir=$(expr "$arg" : '\(.*\).cramfs')
    saxx
    local code=$?
    ;;
  *.deb)
    a_dir=$(expr "$arg" : '\(.*\).deb')
    saxx
    local code=$?
    ;;
  *.dmg)
    a_dir=$(expr "$arg" : '\(.*\).dmg')
    saxx
    local code=$?
    ;;
  *.fat)
    a_dir=$(expr "$arg" : '\(.*\).fat')
    saxx
    local code=$?
    ;;
  *.hfs)
    a_dir=$(expr "$arg" : '\(.*\).hfs')
    saxx
    local code=$?
    ;;
  *.lzh)
    a_dir=$(expr "$arg" : '\(.*\).lzh')
    saxx
    local code=$?
    ;;
  *.lzma)
    a_dir=$(expr "$arg" : '\(.*\).lzma')
    saxx
    local code=$?
    ;;
  *.lzma2)
    a_dir=$(expr "$arg" : '\(.*\).lzma2')
    saxx
    local code=$?
    ;;
  *.mbr)
    a_dir=$(expr "$arg" : '\(.*\).mbr')
    saxx
    local code=$?
    ;;
  *.msi)
    a_dir=$(expr "$arg" : '\(.*\).msi')
    saxx
    local code=$?
    ;;
  *.mslz)
    a_dir=$(expr "$arg" : '\(.*\).mslz')
    saxx
    local code=$?
    ;;
  *.nsis)
    a_dir=$(expr "$arg" : '\(.*\).nsis')
    saxx
    local code=$?
    ;;
  *.ntfs)
    a_dir=$(expr "$arg" : '\(.*\).ntfs')
    saxx
    local code=$?
    ;;
  *.rpm)
    a_dir=$(expr "$arg" : '\(.*\).rpm')
    saxx
    local code=$?
    ;;
  *.squashfs)
    a_dir=$(expr "$arg" : '\(.*\).squashfs')
    saxx
    local code=$?
    ;;
  *.udf)
    a_dir=$(expr "$arg" : '\(.*\).udf')
    saxx
    local code=$?
    ;;
  *.vhd)
    a_dir=$(expr "$arg" : '\(.*\).vhd')
    saxx
    local code=$?
    ;;
  *.xar)
    a_dir=$(expr "$arg" : '\(.*\).xar')
    saxx
    local code=$?
    ;;
  *)
    echo "'$arg' failed" 1>&2
    exit 1
    ;;
  esac
  cd - || exit $?
  exit $code
}

extract "$1" "$2"
